### ISSUE TITLE
bug:  java.lang.NoSuchFieldError: No field textSpacerNoTitle of type I in class Landroid/support/v7/appcompat/R$id; or its superclasses

### ISSUE THREAD

**Issue by naser9878** [stepstone-tech/android-material-app-rating#35]
04-13 22:45:09.151 551-551/ir.example.nbd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.example.nbd, PID: 551
    java.lang.NoSuchFieldError: No field textSpacerNoTitle of type I in class Landroid/support/v7/appcompat/R$id; or its superclasses (declaration of 'android.support.v7.appcompat.R$id' appears in /data/app/ir.example.nbd-2/base.apk)
        at android.support.v7.app.AlertController.setupView(AlertController.java:513)
        at android.support.v7.app.AlertController.installContent(AlertController.java:227)
        at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:260)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
        at android.app.Dialog.show(Dialog.java:314)
        at android.support.v4.app.DialogFragment.onStart(DialogFragment.java:416)
        at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6247)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by paveltech** [comment]
I found this solution. Somehow the library element id and your project id matching. So that they can't find the relevant id. My suggestion will be change your layout element id name.
